version: "3"
services:
    mongodb:
        image: mongo:latest
        command: --port 27000
        ports:
            - 27000:27000
        expose:
            - 27000
    redis:
        image: redis:latest
        command: --port 6380
        ports:
            - 6380:6380
        expose:
            - 6380
        restart: always
    backend-bazinga:
        build: backend
        volumes:
          - ./backend:/src/
          - nodemodules:/src/node_modules
        command: npm run dev
        ports:
            - 4000:4000
        environment:
            URL_MONGO: mongodb:27000
            URL_REDIS: redis://redis:6380
            PORT: 4000
            SALT_HASH: $$2a$$12$$E2hNcmrZaME97zOAUBFPye.9wEJiAVHJ0BhazUjJd9xDQkto6b8w6
        links:
            - mongodb
            - redis
        depends_on:
            - mongodb
            - redis
volumes:
    nodemodules: {}