version: "3"
services:
    mongodb:
        image: mongo:6
        ports:
            - 27000:27017
    backend-bazinga:
        build: backend
        command: npm run dev
        ports:
            - 4000:4000
        environment:
            URL_MONGO: mongodb
            PORT: 4000
        volumes:
          - ./backend:/src/
          - nodemodules:/src/node_modules
        links:
            - mongodb
        depends_on:
            - mongodb
volumes:
    nodemodules: {}